/**
 * Two-way relay between one iMessage group (via Sendblue) and one Slack channel.
 *
 * iMessage -> Slack
 *   Sendblue "receive" webhook -> POST /webhooks/sendblue/<RELAY_TOKEN> -> chat.postMessage with a
 *   *user* token. Posting as a real user (not as the app) matters: Slack flags bot-authored mentions
 *   with subtype "bot_message", which agents such as OpenTag ignore to avoid bot loops.
 *   Each relayed post carries the Sendblue message_handle in a Block Kit block_id so it can be
 *   found again when someone replies to it in a Slack thread.
 *
 * Slack -> iMessage
 *   Slack Events API -> POST /webhooks/slack/events (verified with the signing secret)
 *   -> Sendblue send-group-message. Only messages from OPENTAG_SLACK_USER_ID in SLACK_CHANNEL_ID
 *   are relayed. A thread reply whose parent is a relayed iMessage becomes an iMessage inline reply.
 */

// Only functions and the default handler may be exported from a Worker entry module;
// workerd rejects other named exports at startup.
const SENDBLUE_WEBHOOK_PATH = '/webhooks/sendblue/';
const SLACK_EVENTS_PATH = '/webhooks/slack/events';
const UNSUPPORTED_PLACEHOLDER = '[Unsupported message content]';
const SLACK_POST_TIMEOUT_MS = 10_000;
const SLACK_API_TIMEOUT_MS = 5_000;
const SENDBLUE_API_TIMEOUT_MS = 15_000;
const SLACK_SIGNATURE_MAX_AGE_S = 5 * 60;
const SLACK_SECTION_TEXT_LIMIT = 3000;
const SENDBLUE_SEND_GROUP_URL = 'https://api.sendblue.com/api/send-group-message';
const SLACK_POST_MESSAGE_URL = 'https://slack.com/api/chat.postMessage';
const SLACK_REPLIES_URL = 'https://slack.com/api/conversations.replies';
const RELAY_BLOCK_ID_PREFIX = 'sb:';
const RELAYABLE_SLACK_SUBTYPES = new Set(['', 'bot_message', 'thread_broadcast', 'file_share']);
const SLACK_USER_ID_PATTERN = /^[UW][A-Z0-9]{2,}$/;

/** Subset of the Sendblue message callback that this relay reads. All fields are optional on purpose. */
export interface SendbluePayload {
	message_handle?: unknown;
	group_id?: unknown;
	is_outbound?: unknown;
	from_number?: unknown;
	content?: unknown;
	media_url?: unknown;
}

/** Subset of a Slack `message` event. */
export interface SlackMessageEvent {
	type?: unknown;
	subtype?: unknown;
	hidden?: unknown;
	channel?: unknown;
	user?: unknown;
	bot_id?: unknown;
	app_id?: unknown;
	text?: unknown;
	blocks?: unknown;
	ts?: unknown;
	thread_ts?: unknown;
}

export type SlackFailure = 'rate_limited' | `http_${number}` | `slack_${string}` | 'unexpected_body' | 'timeout' | 'network_error';

type SendResult = { ok: true; messageHandle: string } | { ok: false; category: string };

interface SlackRelayConfig {
	channelId: string;
	senderId: string;
	fromNumber: string;
	groupId: string;
}

/**
 * `Env` (generated by `wrangler types`) only covers the secrets declared in wrangler.jsonc. The
 * identifiers below are deliberately not in that file, since it is committed: they are plain vars
 * set on the Worker itself (`wrangler deploy --var` or the dashboard) and preserved across deploys
 * by `keep_vars`. Each is undefined until configured, which puts the affected direction into
 * discovery mode. SENDER_NAMES is a JSON object when set as a JSON var and a string otherwise.
 */
export interface RelayEnv extends Env {
	ALLOWED_GROUP_ID?: string;
	SENDER_NAMES?: string | Record<string, unknown>;
	SLACK_CHANNEL_ID?: string;
	OPENTAG_SLACK_USER_ID?: string;
	SENDBLUE_FROM_NUMBER?: string;
}

export default {
	async fetch(request, env, ctx): Promise<Response> {
		const url = new URL(request.url);

		if (url.pathname === SLACK_EVENTS_PATH) {
			if (request.method !== 'POST') return methodNotAllowed();
			return handleSlackEvent(request, env, ctx);
		}
		if (url.pathname.startsWith(SENDBLUE_WEBHOOK_PATH)) {
			if (request.method !== 'POST') return methodNotAllowed();
			return handleSendblueWebhook(request, url, env);
		}
		return new Response('Not found', { status: 404 });
	},
} satisfies ExportedHandler<RelayEnv>;

// ---------------------------------------------------------------------------
// iMessage -> Slack
// ---------------------------------------------------------------------------

async function handleSendblueWebhook(request: Request, url: URL, env: RelayEnv): Promise<Response> {
	const presentedToken = url.pathname.slice(SENDBLUE_WEBHOOK_PATH.length);
	if (!tokensMatch(presentedToken, env.RELAY_TOKEN)) {
		log('warn', { event: 'auth_failed' });
		return new Response('Unauthorized', { status: 401 });
	}

	const payload = parseJsonObject(await request.text()) as SendbluePayload | null;
	if (payload === null) {
		log('warn', { event: 'bad_json' });
		return new Response('Bad request', { status: 400 });
	}

	const rawHandle = asString(payload.message_handle);
	const messageHandle = rawHandle || '(none)';
	const groupId = asString(payload.group_id);

	if (payload.is_outbound === true) {
		return ok('Ignored: outbound');
	}

	// Discovery mode: an empty ALLOWED_GROUP_ID must never mean "forward every chat", and without
	// SLACK_CHANNEL_ID there is nowhere to post.
	const missing = [!env.ALLOWED_GROUP_ID && 'ALLOWED_GROUP_ID', !env.SLACK_CHANNEL_ID && 'SLACK_CHANNEL_ID'].filter(Boolean).join(',');
	if (missing.length > 0) {
		log('info', { event: 'discovery', group_id: groupId, message_handle: messageHandle, missing });
		return ok('Discovery mode: not forwarded');
	}

	if (groupId !== env.ALLOWED_GROUP_ID) {
		return ok('Ignored: other chat');
	}

	const text = buildSlackText(payload, parseSenderNames(env.SENDER_NAMES), env.OPENTAG_SLACK_USER_ID);
	const failure = await postToSlack(env, slackMessagePayload(text, rawHandle));
	if (failure !== null) {
		log('error', { event: 'slack_failed', message_handle: messageHandle, category: failure });
		return new Response('Slack delivery failed', { status: 502 });
	}

	return ok('Forwarded');
}

/**
 * Builds the single Slack message body for a matching inbound message.
 *
 * Copied participant text is escaped so it cannot form Slack control sequences
 * (<!channel>, <@U...>, <url|label>); bare URLs are left intact and Slack auto-links them.
 * The one deliberate exception: when `mentionUserId` is configured, a literal "@opentag" written
 * in iMessage becomes a real mention of that user so the agent is actually triggered.
 * A usable media_url is appended on its own line wrapped in <...> so it stays clickable.
 */
export function buildSlackText(payload: SendbluePayload, names: Readonly<Record<string, string>>, mentionUserId = ''): string {
	const fromNumber = asString(payload.from_number);
	const sender = escapeSlack(names[fromNumber] ?? (fromNumber.length > 0 ? fromNumber : 'Unknown sender'));
	const content = asString(payload.content);
	const mediaUrl = usableMediaUrl(asString(payload.media_url));

	if (content.length === 0 && mediaUrl === null) {
		return `${sender}: ${UNSUPPORTED_PLACEHOLDER}`;
	}

	let body = escapeSlack(content);
	if (SLACK_USER_ID_PATTERN.test(mentionUserId)) {
		body = body.replace(/(^|[^\w@])@opentag\b/gi, `$1<@${mentionUserId}>`);
	}

	let text = content.length > 0 ? `${sender}: ${body}` : `${sender}:`;
	if (mediaUrl !== null) {
		text += `\nAttachment: <${mediaUrl}>`;
	}
	return text;
}

export function escapeSlack(value: string): string {
	return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

/**
 * chat.postMessage payload (minus the channel). When possible the text is also sent as a section block
 * whose block_id carries the Sendblue handle; Slack stores block_ids, so a later thread reply can be mapped back.
 */
export function slackMessagePayload(text: string, messageHandle: string): Record<string, unknown> {
	const payload: Record<string, unknown> = { text, link_names: false };
	if (messageHandle.length > 0 && messageHandle.length <= 200 && text.length <= SLACK_SECTION_TEXT_LIMIT) {
		payload.blocks = [{ type: 'section', block_id: RELAY_BLOCK_ID_PREFIX + messageHandle, text: { type: 'mrkdwn', text } }];
	}
	return payload;
}

/**
 * Normalizes the SENDER_NAMES binding into a number -> name map.
 * Accepts a JSON object (dashboard "JSON" var) or a JSON string (`wrangler deploy --var`, "Text" var);
 * anything else, including malformed JSON, yields an empty map so senders fall back to their number.
 */
export function parseSenderNames(value: unknown): Readonly<Record<string, string>> {
	let candidate: unknown = value;
	if (typeof candidate === 'string') {
		try {
			candidate = JSON.parse(candidate);
		} catch {
			return {};
		}
	}
	if (!isObject(candidate)) return {};

	const names: Record<string, string> = {};
	for (const [number, name] of Object.entries(candidate)) {
		if (typeof name === 'string' && name.trim().length > 0) names[number] = name.trim();
	}
	return names;
}

/** Returns a normalized http(s) URL, or null when the value cannot be turned into a clickable link. */
function usableMediaUrl(value: string): string | null {
	if (value.length === 0) return null;
	try {
		const parsed = new URL(value);
		if (parsed.protocol !== 'https:' && parsed.protocol !== 'http:') return null;
		// `<` `>` `|` would terminate or relabel the Slack link; encoding keeps the link intact.
		return parsed.href.replaceAll('<', '%3C').replaceAll('>', '%3E').replaceAll('|', '%7C');
	} catch {
		return null;
	}
}

/**
 * Posts into SLACK_CHANNEL_ID via chat.postMessage as the user who installed the app, and waits
 * for the verdict. Returns null on success (`{"ok":true}`), otherwise a failure category; Slack API
 * errors (not_in_channel, invalid_auth, ...) surface as `slack_<error>`.
 */
async function postToSlack(env: RelayEnv, payload: Record<string, unknown>): Promise<SlackFailure | null> {
	let response: Response;
	try {
		response = await fetch(SLACK_POST_MESSAGE_URL, {
			method: 'POST',
			headers: { 'content-type': 'application/json; charset=utf-8', authorization: `Bearer ${env.SLACK_USER_TOKEN}` },
			body: JSON.stringify({ channel: env.SLACK_CHANNEL_ID, ...payload }),
			signal: AbortSignal.timeout(SLACK_POST_TIMEOUT_MS),
		});
	} catch (error) {
		return isTimeout(error) ? 'timeout' : 'network_error';
	}

	if (response.status === 429) return 'rate_limited';
	if (!response.ok) return `http_${response.status}`;

	const data = parseJsonObject(await response.text().catch(() => ''));
	if (data === null) return 'unexpected_body';
	if (data.ok !== true) {
		const error = asString(data.error) || 'unknown_error';
		return error === 'ratelimited' ? 'rate_limited' : `slack_${error}`;
	}
	return null;
}

// ---------------------------------------------------------------------------
// Slack -> iMessage
// ---------------------------------------------------------------------------

async function handleSlackEvent(request: Request, env: RelayEnv, ctx: ExecutionContext): Promise<Response> {
	const rawBody = await request.text();
	const verified = await verifySlackSignature(
		env.SLACK_SIGNING_SECRET,
		request.headers.get('x-slack-request-timestamp'),
		request.headers.get('x-slack-signature'),
		rawBody,
	);
	if (!verified) {
		log('warn', { event: 'slack_auth_failed' });
		return new Response('Unauthorized', { status: 401 });
	}

	const body = parseJsonObject(rawBody);
	if (body === null) {
		log('warn', { event: 'slack_bad_json' });
		return new Response('Bad request', { status: 400 });
	}

	if (body.type === 'url_verification') {
		return new Response(JSON.stringify({ challenge: asString(body.challenge) }), {
			status: 200,
			headers: { 'content-type': 'application/json' },
		});
	}
	if (body.type !== 'event_callback' || !isObject(body.event)) {
		return ok('Ignored: not an event callback');
	}

	const event = body.event as SlackMessageEvent;
	if (event.type !== 'message') return ok('Ignored: not a message');
	const subtype = asString(event.subtype);
	if (event.hidden === true || !RELAYABLE_SLACK_SUBTYPES.has(subtype)) return ok('Ignored: message subtype');

	const channel = asString(event.channel);
	const user = asString(event.user);
	const botId = asString(event.bot_id);
	const appId = asString(event.app_id);
	const ts = asString(event.ts);
	const threadTs = asString(event.thread_ts);

	// Discovery mode: until the channel, sender, group and sending number are all configured,
	// log identifiers so they can be copied into wrangler.jsonc, and relay nothing.
	const config = slackRelayConfig(env);
	if (config === null) {
		log('info', { event: 'slack_discovery', channel, user, bot_id: botId, app_id: appId, subtype, ts, thread_ts: threadTs });
		return ok('Discovery mode: not relayed');
	}

	if (channel !== config.channelId) return ok('Ignored: other channel');
	// Accept the member ID (U...), bot ID (B...) or app ID (A...); only the member ID also enables the mention.
	if (user !== config.senderId && botId !== config.senderId && appId !== config.senderId) return ok('Ignored: other sender');

	const text = slackEventText(event);
	if (text.length === 0) {
		log('info', { event: 'slack_relay_skipped', slack_ts: ts, category: 'no_text' });
		return ok('Ignored: no text');
	}

	// Slack retries anything not acknowledged within 3 seconds, so acknowledge now and deliver after.
	ctx.waitUntil(relayToGroup(env, config, { text, ts, threadTs, channel }));
	return ok('Accepted');
}

function slackRelayConfig(env: RelayEnv): SlackRelayConfig | null {
	const channelId = asString(env.SLACK_CHANNEL_ID);
	const senderId = asString(env.OPENTAG_SLACK_USER_ID);
	const fromNumber = asString(env.SENDBLUE_FROM_NUMBER);
	const groupId = asString(env.ALLOWED_GROUP_ID);
	if (!channelId || !senderId || !fromNumber || !groupId) return null;
	return { channelId, senderId, fromNumber, groupId };
}

async function relayToGroup(
	env: RelayEnv,
	config: SlackRelayConfig,
	message: { text: string; ts: string; threadTs: string; channel: string },
): Promise<void> {
	let replyTo: string | null = null;
	if (message.threadTs.length > 0 && message.threadTs !== message.ts) {
		replyTo = await lookupRelayedHandle(env.SLACK_USER_TOKEN, message.channel, message.threadTs);
	}

	let result = await sendGroupMessage(env, config, message.text, replyTo);
	if (!result.ok && replyTo !== null && result.category.startsWith('http_4')) {
		// Sendblue rejects inline replies it cannot honor (400); deliver as a plain message instead.
		log('warn', { event: 'reply_rejected', slack_ts: message.ts, category: result.category });
		replyTo = null;
		result = await sendGroupMessage(env, config, message.text, null);
	}

	if (result.ok) {
		log('info', { event: 'slack_relayed', slack_ts: message.ts, inline_reply: String(replyTo !== null), message_handle: result.messageHandle });
	} else {
		log('error', { event: 'slack_relay_failed', slack_ts: message.ts, category: result.category });
	}
}

/** Finds the Sendblue handle hidden in a relayed post's block_id, given the Slack thread parent ts. */
async function lookupRelayedHandle(token: string, channel: string, threadTs: string): Promise<string | null> {
	const params = new URLSearchParams({ channel, ts: threadTs, limit: '1', inclusive: 'true' });
	let response: Response;
	try {
		response = await fetch(`${SLACK_REPLIES_URL}?${params}`, {
			headers: { authorization: `Bearer ${token}` },
			signal: AbortSignal.timeout(SLACK_API_TIMEOUT_MS),
		});
	} catch (error) {
		log('warn', { event: 'thread_lookup_failed', category: isTimeout(error) ? 'timeout' : 'network_error' });
		return null;
	}
	if (!response.ok) {
		log('warn', { event: 'thread_lookup_failed', category: `http_${response.status}` });
		return null;
	}

	const data = parseJsonObject(await response.text().catch(() => ''));
	if (data === null || data.ok !== true || !Array.isArray(data.messages)) {
		log('warn', { event: 'thread_lookup_failed', category: data !== null ? asString(data.error) || 'not_ok' : 'bad_json' });
		return null;
	}
	const parent = data.messages.find((m) => isObject(m) && asString(m.ts) === threadTs) ?? data.messages[0];
	return extractRelayedHandle(parent);
}

export function extractRelayedHandle(message: unknown): string | null {
	if (!isObject(message) || !Array.isArray(message.blocks)) return null;
	for (const block of message.blocks) {
		if (!isObject(block)) continue;
		const blockId = asString(block.block_id);
		if (blockId.length > RELAY_BLOCK_ID_PREFIX.length && blockId.startsWith(RELAY_BLOCK_ID_PREFIX)) {
			return blockId.slice(RELAY_BLOCK_ID_PREFIX.length);
		}
	}
	return null;
}

async function sendGroupMessage(env: RelayEnv, config: SlackRelayConfig, content: string, replyToHandle: string | null): Promise<SendResult> {
	const body: Record<string, unknown> = { group_id: config.groupId, from_number: config.fromNumber, content };
	if (replyToHandle !== null) body.reply_to = { message_handle: replyToHandle };

	let response: Response;
	try {
		response = await fetch(SENDBLUE_SEND_GROUP_URL, {
			method: 'POST',
			headers: {
				'content-type': 'application/json',
				'sb-api-key-id': env.SENDBLUE_API_KEY_ID,
				'sb-api-secret-key': env.SENDBLUE_API_SECRET_KEY,
			},
			body: JSON.stringify(body),
			signal: AbortSignal.timeout(SENDBLUE_API_TIMEOUT_MS),
		});
	} catch (error) {
		return { ok: false, category: isTimeout(error) ? 'timeout' : 'network_error' };
	}

	if (response.status === 429) return { ok: false, category: 'rate_limited' };
	if (!response.ok) return { ok: false, category: `http_${response.status}` };

	const data = parseJsonObject(await response.text().catch(() => ''));
	if (data !== null && asString(data.status) === 'ERROR') return { ok: false, category: 'sendblue_error' };
	return { ok: true, messageHandle: data !== null ? asString(data.message_handle) : '' };
}

/** Plain text for iMessage from a Slack message event: `text` first, rich_text blocks as a fallback. */
function slackEventText(event: SlackMessageEvent): string {
	const text = asString(event.text).trim();
	if (text.length > 0) return slackMarkupToPlainText(text);
	return slackMarkupToPlainText(richTextFromBlocks(event.blocks)).trim();
}

/** Converts Slack mrkdwn entities (<@U..>, <#C..|name>, <!here>, <url|label>, &amp;) into plain text. */
export function slackMarkupToPlainText(text: string): string {
	return text
		.replace(/<@([A-Z0-9]+)(?:\|([^>]*))?>/g, (_m, id: string, label?: string) => `@${label || id}`)
		.replace(/<#([A-Z0-9]+)(?:\|([^>]*))?>/g, (_m, id: string, label?: string) => `#${label || id}`)
		.replace(/<!(channel|here|everyone)(?:\|[^>]*)?>/g, '@$1')
		.replace(/<!subteam\^[A-Z0-9]+(?:\|@?([^>]*))?>/g, (_m, label?: string) => `@${label || 'group'}`)
		.replace(/<!date\^\d+\^[^|>]*(?:\|([^>]*))?>/g, (_m, fallback?: string) => fallback ?? '')
		.replace(/<((?:mailto|tel):([^|>]*))(?:\|([^>]*))?>/g, (_m, _full: string, target: string, label?: string) => label || target)
		.replace(/<(https?:[^|>]*)\|([^>]*)>/g, (_m, url: string, label: string) => (label && label !== url ? `${label} (${url})` : url))
		.replace(/<(https?:[^>]*)>/g, '$1')
		.replaceAll('&lt;', '<')
		.replaceAll('&gt;', '>')
		.replaceAll('&amp;', '&');
}

function richTextFromBlocks(blocks: unknown): string {
	if (!Array.isArray(blocks)) return '';
	const out: string[] = [];
	const walk = (node: unknown): void => {
		if (Array.isArray(node)) {
			for (const child of node) walk(child);
			return;
		}
		if (!isObject(node)) return;
		switch (node.type) {
			case 'text':
				out.push(asString(node.text));
				return;
			case 'link':
				out.push(asString(node.text) || asString(node.url));
				return;
			case 'user':
				out.push(`@${asString(node.user_id)}`);
				return;
			case 'channel':
				out.push(`#${asString(node.channel_id)}`);
				return;
			case 'emoji':
				out.push(`:${asString(node.name)}:`);
				return;
			case 'broadcast':
				out.push(`@${asString(node.range)}`);
				return;
			case 'rich_text_section':
			case 'rich_text_preformatted':
			case 'rich_text_quote':
				walk(node.elements);
				out.push('\n');
				return;
			case 'rich_text_list':
				for (const item of Array.isArray(node.elements) ? node.elements : []) {
					out.push('- ');
					walk(item);
				}
				return;
			case 'section':
				out.push(isObject(node.text) ? asString(node.text.text) : '', '\n');
				return;
			default:
				walk(node.elements);
		}
	};
	walk(blocks);
	return out.join('');
}

/** Slack request signing: v0=HMAC-SHA256(secret, "v0:<timestamp>:<raw body>"), rejecting stale timestamps. */
export async function verifySlackSignature(
	signingSecret: string | undefined,
	timestampHeader: string | null,
	signatureHeader: string | null,
	rawBody: string,
): Promise<boolean> {
	if (!signingSecret || !timestampHeader || !signatureHeader) return false;
	const timestamp = Number(timestampHeader);
	if (!Number.isFinite(timestamp) || Math.abs(Date.now() / 1000 - timestamp) > SLACK_SIGNATURE_MAX_AGE_S) return false;

	const encoder = new TextEncoder();
	const key = await crypto.subtle.importKey('raw', encoder.encode(signingSecret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
	const mac = await crypto.subtle.sign('HMAC', key, encoder.encode(`v0:${timestampHeader}:${rawBody}`));
	const expected = `v0=${toHex(new Uint8Array(mac))}`;
	return tokensMatch(signatureHeader, expected);
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/** Constant-time comparison; an empty expected value never matches. */
function tokensMatch(presented: string, expected: string | undefined): boolean {
	if (!expected || presented.length === 0) return false;
	const encoder = new TextEncoder();
	const a = encoder.encode(presented);
	const b = encoder.encode(expected);
	if (a.byteLength !== b.byteLength) return false;
	return crypto.subtle.timingSafeEqual(a, b);
}

function toHex(bytes: Uint8Array): string {
	let hex = '';
	for (const byte of bytes) hex += byte.toString(16).padStart(2, '0');
	return hex;
}

function parseJsonObject(raw: string): Record<string, unknown> | null {
	try {
		const parsed: unknown = JSON.parse(raw);
		return isObject(parsed) ? parsed : null;
	} catch {
		return null;
	}
}

function isObject(value: unknown): value is Record<string, unknown> {
	return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function asString(value: unknown): string {
	return typeof value === 'string' ? value : '';
}

function isTimeout(error: unknown): boolean {
	return error instanceof Error && error.name === 'TimeoutError';
}

function ok(message: string): Response {
	return new Response(message, { status: 200 });
}

function methodNotAllowed(): Response {
	return new Response('Method not allowed', { status: 405, headers: { allow: 'POST' } });
}

/** Structured log line. Callers must only pass identifiers and categories, never tokens, URLs, or message text. */
function log(level: 'info' | 'warn' | 'error', fields: Record<string, string>): void {
	const line = JSON.stringify(fields);
	if (level === 'error') console.error(line);
	else if (level === 'warn') console.warn(line);
	else console.log(line);
}
